max_retries = 10
ping_duration = "1000s"
tick_duration = "2s"
num_bundle = 10

contract_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

ignore_median_errors = false
tick_event_type = "ojo.oracle.v1.EventSetFxRate"
max_gas_units = 1000000000

[account]
acc_prefix = "wasm"
chain_id = "wasm-test"
address = "wasm1usr9g5a4s2qrwl63sdjtrs2qd4a7huh6qksawp"

[keyring]
backend = "test"
dir = "./"

[target_rpc]
tmrpc_endpoint = ["http://localhost:26657"]
rpc_timeout = "2000ms"
query_endpoint = ["0.0.0.0:9090"]

[data_rpc]
query_rpcs = ["api.agamotto-val-stage-0.ojo.network:9090"]
event_rpcs = ["https://rpc.agamotto-val-stage-0.ojo.network:443"]

[timeout]
event_timeout = "1000ms"
max_tick_timeout = "500s"
query_timeout = "3000ms"
timeout_height = 10
provider_timeout = ""

[gas]
gas_adjustment = 1.5
gas_prices = "0.2stake"
gas_per_tx = 100000000000

[tx_config]
total_tx_threshold=5
total_gas_threshold= 10000000
max_tx_duration = "100s"
max_gas_per_tx = 10000
max_timeout = "2s"

[block_height_config]
skip_error = false